trigger: 
 - main

jobs:
- job: Testing
  displayName: 'Testing Azure Conection'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  

  - task: AzureCLI@2
    displayName: 'Login to Azure'
    inputs:
      azureSubscription: 'ADO-Azure(025-Dev-App-1)-Service Connection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login --tenant $(tenant_id)
        az account set --subscription $(subscription_id)
        az group list --output table
        echo "Azure connection successful!"

